### ISSUE TITLE
Frame ID `lidar_link` doesn't exist

### ISSUE THREAD

**Issue by IamPhytan** [norlab-ulaval/marmotte_mapping#3]
It seems that the `lslidar_c16` launch file was changed recently, yet the `frame_id` of the lidar was not set properly.

https://github.com/norlab-ulaval/marmotte_mapping/blob/4d50e1fe0495f998851d8d5388fea85f9e5b7a17/launch/lslidar_c16.launch.xml#L10

**Comment by boxanm** [comment]
I don't see any issue, the `lidar_link` frame is [in marmotte's sensor urdf](https://github.com/norlab-ulaval/marmotte_description/blob/92ab3a21756478365048694e0ef5829faa8d6b99/urdf/sensors.urdf.xacro#L74): 
` <link name="lidar_link"/>`
